#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CnMedicineServer")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertSurveysAnswerTemplates(SurveysAnswerTemplates instance);
    partial void UpdateSurveysAnswerTemplates(SurveysAnswerTemplates instance);
    partial void DeleteSurveysAnswerTemplates(SurveysAnswerTemplates instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::HelpTest.Properties.Settings.Default.CnMedicineServerConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SurveysAnswerTemplates> SurveysAnswerTemplates
		{
			get
			{
				return this.GetTable<SurveysAnswerTemplates>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SurveysAnswerTemplates")]
	public partial class SurveysAnswerTemplates : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Guid _SurveysQuestionTemplateId;
		
		private string _AnswerTitle;
		
		private int _OrderNum;
		
		private bool _AllowAdditional;
		
		private string _Name;
		
		private string _ShortName;
		
		private string _Description;
		
		private System.DateTime _CreateUtc;
		
		private string _UserState;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnSurveysQuestionTemplateIdChanging(System.Guid value);
    partial void OnSurveysQuestionTemplateIdChanged();
    partial void OnAnswerTitleChanging(string value);
    partial void OnAnswerTitleChanged();
    partial void OnOrderNumChanging(int value);
    partial void OnOrderNumChanged();
    partial void OnAllowAdditionalChanging(bool value);
    partial void OnAllowAdditionalChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnShortNameChanging(string value);
    partial void OnShortNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnCreateUtcChanging(System.DateTime value);
    partial void OnCreateUtcChanged();
    partial void OnUserStateChanging(string value);
    partial void OnUserStateChanged();
    #endregion
		
		public SurveysAnswerTemplates()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SurveysQuestionTemplateId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid SurveysQuestionTemplateId
		{
			get
			{
				return this._SurveysQuestionTemplateId;
			}
			set
			{
				if ((this._SurveysQuestionTemplateId != value))
				{
					this.OnSurveysQuestionTemplateIdChanging(value);
					this.SendPropertyChanging();
					this._SurveysQuestionTemplateId = value;
					this.SendPropertyChanged("SurveysQuestionTemplateId");
					this.OnSurveysQuestionTemplateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerTitle", DbType="NVarChar(MAX)")]
		public string AnswerTitle
		{
			get
			{
				return this._AnswerTitle;
			}
			set
			{
				if ((this._AnswerTitle != value))
				{
					this.OnAnswerTitleChanging(value);
					this.SendPropertyChanging();
					this._AnswerTitle = value;
					this.SendPropertyChanged("AnswerTitle");
					this.OnAnswerTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNum", DbType="Int NOT NULL")]
		public int OrderNum
		{
			get
			{
				return this._OrderNum;
			}
			set
			{
				if ((this._OrderNum != value))
				{
					this.OnOrderNumChanging(value);
					this.SendPropertyChanging();
					this._OrderNum = value;
					this.SendPropertyChanged("OrderNum");
					this.OnOrderNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowAdditional", DbType="Bit NOT NULL")]
		public bool AllowAdditional
		{
			get
			{
				return this._AllowAdditional;
			}
			set
			{
				if ((this._AllowAdditional != value))
				{
					this.OnAllowAdditionalChanging(value);
					this.SendPropertyChanging();
					this._AllowAdditional = value;
					this.SendPropertyChanged("AllowAdditional");
					this.OnAllowAdditionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="NVarChar(8)")]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this.OnShortNameChanging(value);
					this.SendPropertyChanging();
					this._ShortName = value;
					this.SendPropertyChanged("ShortName");
					this.OnShortNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUtc", DbType="DateTime NOT NULL")]
		public System.DateTime CreateUtc
		{
			get
			{
				return this._CreateUtc;
			}
			set
			{
				if ((this._CreateUtc != value))
				{
					this.OnCreateUtcChanging(value);
					this.SendPropertyChanging();
					this._CreateUtc = value;
					this.SendPropertyChanged("CreateUtc");
					this.OnCreateUtcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserState", DbType="NVarChar(MAX)")]
		public string UserState
		{
			get
			{
				return this._UserState;
			}
			set
			{
				if ((this._UserState != value))
				{
					this.OnUserStateChanging(value);
					this.SendPropertyChanging();
					this._UserState = value;
					this.SendPropertyChanged("UserState");
					this.OnUserStateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
